### ISSUE TITLE
Bitmap color search functions raise TypeError

### ISSUE THREAD

**Issue by L1nkus** [autopilot-rs/autopy#49]
The following functions:
find_color
find_every_color
count_of_color

cause this:

```
>>> import autopy
>>> autopy.bitmap.capture_screen().find_color(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError
```

**Comment by msanders** [comment]
Thanks for reporting this. It looks like these weren't updated to use hex values for colors instead of tuples. I'll fix it in the next release. For now you can workaround it with this:

```python
import autopy
autopy.bitmap.capture_screen().find_color(autopy.color.hex_to_rgb(0))
```

**Comment by msanders** [comment]
Fixed by https://github.com/autopilot-rs/autopy/commit/0b60f223b54bf86f9e73d75b666ff3b94b752300, release in 4.0.0.

**Comment by Danferno** [comment]
I think the documentation is still wrong? It says the function expects a Tuple[int, int, int] but actually expects the hex value

``` count_of_color(color: Tuple[int, int, int], tolerance: float=None, rect: Tuple[Tuple[float, float], Tuple[float, float]]=None, start_point: Tuple[float, float]=None) → int ```

On version 4.0.1
